# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'onMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  #pod 'FirebaseUI'
  # Pods for onMap

  target 'onMapTests' do
    
  end

  target 'onMapUITests' do
    # Pods for testing
  end

end
