# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnMap
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'RealmSwift'
  

  target 'OnMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
